apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    label-one: "test-IaC"
  name: computenetwork-iac
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
