cloudbilling.googleapis.com
--
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    cnrm.cloud.google.com/organization-id: "0"
    cnrm.cloud.google.com/auto-create-network: "false"
  labels:
    label-one: "IaaC-tests"
  name: project-sample-1
spec:
  name: Sample-project
  billingAccountRef:
    # Replace "${BILLING_ACCOUNT_ID?}" with the numeric ID for your billing account
    external: "019D7C-1E9133-142512"