apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: iac-network
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false  
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "test-IaC"
  name: subnetwork-iac-development
spec:
  ipCidrRange: 10.100.18.0/24
  region: us-east1
  description: My third IaC subnet
  privateIpGoogleAccess: false
  networkRef:
    name: iac-network
  logConfig:
    aggregationInterval: INTERVAL_15_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA    
