apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "test-IaC2"
  name: subnetwork-iac-sample
spec:
  ipCidrRange: 10.84.1.0/24
  region: us-central1
  description: My first subnet
  privateIpGoogleAccess: false
  networkRef:
    name: computenetwork-iac
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA