apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "cloudbuild"
  name: subnetwork-iac-endpoints
spec:
  ipCidrRange: 10.192.169.0/24
  region: us-east1
  description: Subnet for DB endpoints
  privateIpGoogleAccess: false
  networkRef:
    name: iac-operationtest1
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA