apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  labels:
    label-one: "iac-test"
  name: sql-db-iac-cloudbuild
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: sql-instace-ins2
